version: '3.3'
services:

  pg_db:
    image: postgres:14
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/
    restart: always
    container_name: pg_db
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
